/* CRIAR UMA BASE DE DADOS NOVA */
CREATE DATABASE aula;
/* DELETAR UMA BASE DE DADOS */
DROP DATABASE aula;
/* CRIO UMA DATABASE SE ELA EXISTIR */
CREATE DATABASE IF NOT EXISTS aula;
/* UTILIZAR UMA DATABASE EXISTENTE (ENETRAR NESSA DATABASE) */
USE aula;

/* CRIAR A NOSSA PRIMEIRA TABELA - ENTIDADE - ALUNO */
/*ID, NOME, IDADE*/

CREATE TABLE alunos(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nome VARCHAR(100) NOT NULL,
idade INT NOT NULL
);
/* MOSTRA AS TABELAS CRIADAS */
SHOW TABLES;
/* DESCREVER UMA TABELA */
DESCRIBE alunos;
/* Inserir três valores na minha tabela alunos */
INSERT INTO alunos(id,nome, idade)
VALUES
(6,"Fabricio",32);

DROP TABLE alunos;
/* VISUALIZAR OS DADOS QUE ESTÃO NA MINHA TABELA*/
SELECT * FROM alunos;